// Playwright: every test is recorded (video + trace + screenshot) under a
// generated config that extends the customer's, never edits it. Playwright's
// own retries give fresh contexts per attempt and mark pass-after-retry `flaky`.
import { createRequire } from "node:module";
import { existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { classifyPlaywrightError } from "../classify.js";
import { runCommand } from "../exec.js";
import { log } from "../log.js";
import type { AttemptStatus, DevasignVerifyConfig, LocalArtifact, PlanTest, RunnerAttempt, RunnerResult } from "../types.js";
import type { Workspace } from "../workspace.js";

const require = createRequire(import.meta.url);

export function playwrightCli(root: string): { cmd: string; args: string[]; ours: boolean } {
  const local = path.join(root, "node_modules", "@playwright", "test", "cli.js");
  if (existsSync(local)) return { cmd: process.execPath, args: [local], ours: false };
  return { cmd: process.execPath, args: [require.resolve("@playwright/test/cli")], ours: true };
}

export function ourPlaywrightDir(): string {
  return path.dirname(require.resolve("@playwright/test/package.json"));
}

export type ConfigArgs = {
  root: string;
  baseConfigRel: string | null; // customer's config, repo-relative
  testDir: string; // absolute
  outputDir: string; // absolute
  reportFile: string; // absolute
  retries: number;
  webServer?: { command: string; url: string; baseUrl: string; timeoutMs?: number } | null;
};

/** The generated config source. Spreads the customer's config; forces recording. */
export function generatePlaywrightConfig(a: ConfigArgs): string {
  const j = (v: unknown) => JSON.stringify(v);
  const baseImport = a.baseConfigRel ? `import __base from ${j(path.resolve(a.root, a.baseConfigRel))};` : "const __base: any = {};";
  return [
    "// Generated by @devasign/verify — disposable; the repository's own config is untouched.",
    'import { defineConfig } from "@playwright/test";',
    baseImport,
    "const b: any = (__base as any)?.default ?? __base ?? {};",
    "// One browser project only: recordings once, and no browsers we did not install.",
    "// Project fields win over config fields in Playwright, so the customer's own",
    "// testDir/retries/recording settings are stripped and ours are re-applied here;",
    "// dependencies/teardown would reference projects we did not keep.",
    "const __pick = (ps: any[]) => ps.find((p: any) => /chrom/i.test(String(p?.name || ''))) ?? ps[0];",
    "const __clean = (p: any) => {",
    "  const q: any = { ...p };",
    "  for (const k of ['dependencies', 'teardown', 'testDir', 'testMatch', 'testIgnore', 'retries', 'outputDir', 'grep', 'grepInvert', 'snapshotDir']) delete q[k];",
    "  q.use = { ...(q.use || {}), video: 'on', trace: 'on', screenshot: 'on' };",
    "  return q;",
    "};",
    "const projects = Array.isArray(b.projects) && b.projects.length ? [__clean(__pick(b.projects))] : undefined;",
    "export default defineConfig({",
    "  ...b,",
    `  testDir: ${j(a.testDir)},`,
    "  testMatch: /.*\\.(spec|test)\\.[cjm]?[jt]sx?$/,",
    `  retries: ${a.retries},`,
    `  outputDir: ${j(a.outputDir)},`,
    `  reporter: [["json", { outputFile: ${j(a.reportFile)} }], ["list"]],`,
    "  ...(projects ? { projects } : {}),",
    `  use: { ${a.webServer ? `baseURL: ${j(a.webServer.baseUrl)}, ` : ""}...(b.use || {}), video: "on", trace: "on", screenshot: "on" },`,
    a.webServer
      ? `  webServer: b.webServer ?? { command: ${j(a.webServer.command)}, url: ${j(a.webServer.url)}, cwd: ${j(a.root)}, reuseExistingServer: true, timeout: ${a.webServer.timeoutMs ?? 120_000} },`
      : "",
    "});",
    "",
  ]
    .filter((l) => l !== "")
    .join("\n");
}

export function webServerFromYml(yml: DevasignVerifyConfig | null): ConfigArgs["webServer"] {
  if (!yml?.start || !yml?.url) return null;
  const parts = [yml.install, yml.build, yml.seed, yml.start].filter(Boolean);
  return { command: parts.join(" && "), url: yml.ready ? new URL(yml.ready, yml.url).toString() : yml.url, baseUrl: yml.url };
}

// ---- JSON report → results ---------------------------------------------------

type PwAttachment = { name?: string; contentType?: string; path?: string };
type PwResult = { status: string; retry?: number; duration?: number; error?: { message?: string } | null; errors?: Array<{ message?: string }>; attachments?: PwAttachment[] };
type PwTest = { status?: string; results?: PwResult[]; projectName?: string };
type PwSpec = { title?: string; file?: string; tests?: PwTest[] };
type PwSuite = { title?: string; file?: string; specs?: PwSpec[]; suites?: PwSuite[] };
export type PwReport = { suites?: PwSuite[]; errors?: Array<{ message?: string }> };

export function flattenSpecs(report: PwReport): Array<{ file: string; title: string; tests: PwTest[] }> {
  const out: Array<{ file: string; title: string; tests: PwTest[] }> = [];
  const walk = (s: PwSuite, file: string) => {
    const f = s.file || file;
    for (const sp of s.specs || []) out.push({ file: sp.file || f, title: sp.title || "", tests: sp.tests || [] });
    for (const c of s.suites || []) walk(c, f);
  };
  for (const s of report.suites || []) walk(s, s.file || "");
  return out;
}

function pathsMatch(reportFile: string, planned: string): boolean {
  const a = reportFile.split(path.sep).join("/");
  const b = planned.split(path.sep).join("/");
  return a === b || a.endsWith("/" + b) || b.endsWith("/" + a) || path.posix.basename(a) === path.posix.basename(b);
}

export function stripAnsi(s: string): string {
  return s.replace(/\u001b\[[0-9;]*m/g, "");
}

const KIND_BY_ATTACHMENT: Record<string, LocalArtifact["kind"] | undefined> = { video: "video", trace: "trace", screenshot: "screenshot" };
const TYPE_BY_KIND: Record<string, string> = { video: "video/webm", trace: "application/zip", screenshot: "image/png" };

/** A single test() block: its last retry decides, an earlier failure makes it flaky. */
export function testOutcome(retries: AttemptStatus[]): "pass" | "fail" | "flaky" | "error" {
  if (!retries.length) return "error";
  const last = retries[retries.length - 1];
  if (last === "pass") return retries.every((s) => s === "pass") ? "pass" : "flaky";
  return retries.includes("fail") ? "fail" : "error";
}

/** The file's status is its worst test's: one real failure is a failure, not a flake. */
export function fileStatus(perTest: AttemptStatus[][]): "pass" | "fail" | "flaky" | "error" {
  const outcomes = perTest.map(testOutcome);
  if (!outcomes.length) return "error";
  if (outcomes.includes("fail")) return "fail";
  if (outcomes.includes("flaky")) return "flaky";
  if (outcomes.includes("error")) return "error";
  return "pass";
}

/** One RunnerResult per planned Playwright file, attempts from the report's per-retry results. */
export function mapReport(report: PwReport, tests: PlanTest[], ws: Workspace, artifacts: LocalArtifact[], overallOutput: string): RunnerResult[] {
  const specs = flattenSpecs(report);
  const results: RunnerResult[] = [];
  for (const t of tests) {
    const mine = specs.filter((s) => pathsMatch(s.file, t.path));
    const attempts: RunnerAttempt[] = [];
    let n = 0;
    let anyResult = false;
    // Playwright retries live inside ONE test's results[]; separate test() blocks
    // in the same file are independent outcomes, not attempts at the same thing.
    const perTest: AttemptStatus[][] = [];
    for (const spec of mine) {
      for (const pt of spec.tests) {
        const own: AttemptStatus[] = [];
        perTest.push(own);
        for (const r of [...(pt.results || [])].sort((x, y) => (x.retry ?? 0) - (y.retry ?? 0))) {
          anyResult = true;
          n += 1;
          const message = r.error?.message || r.errors?.[0]?.message;
          let status: AttemptStatus;
          if (r.status === "passed") status = "pass";
          else if (r.status === "skipped") status = "error";
          else status = classifyPlaywrightError(message);
          const refs: string[] = [];
          let videoRef: string | null = null;
          let screenshotPath: string | null = null;
          for (const att of r.attachments || []) {
            const kind = KIND_BY_ATTACHMENT[att.name || ""];
            if (!kind || !att.path || !existsSync(att.path)) continue;
            const ref = `${kind}:${t.id}:${n}:${refs.length}`;
            artifacts.push({ clientRef: ref, kind, path: att.path, displayPath: ws.relative(att.path), contentType: att.contentType || TYPE_BY_KIND[kind], testId: t.id, criterionIds: t.criterionIds, attempt: n });
            refs.push(ref);
            if (kind === "video") videoRef = ref;
            if (kind === "screenshot" && !screenshotPath) screenshotPath = att.path;
          }
          if (videoRef && screenshotPath) {
            // The attempt's end-state screenshot doubles as its recording's poster frame.
            const posterRef = `poster:${t.id}:${n}`;
            artifacts.push({ clientRef: posterRef, kind: "poster", path: screenshotPath, displayPath: ws.relative(screenshotPath), contentType: "image/png", testId: t.id, criterionIds: t.criterionIds, attempt: n, posterFor: videoRef });
            refs.push(posterRef);
          }
          own.push(status);
          attempts.push({ n, status, durationMs: Math.round(r.duration ?? 0), error: status === "pass" ? undefined : stripAnsi(message || r.status).split("\n").slice(0, 3).join(" ").slice(0, 500), artifactIds: refs });
        }
      }
    }
    if (!anyResult) {
      const err = report.errors?.[0]?.message || overallOutput.split("\n").find((l) => /Error|error/.test(l)) || "no result for this test";
      attempts.push({ n: 1, status: "error", durationMs: 0, error: err.slice(0, 500), artifactIds: [] });
      perTest.push(["error"]);
    }
    const status = fileStatus(perTest.filter((t) => t.length));
    results.push({
      id: `r-${t.id}`,
      testId: t.id,
      criterionIds: t.criterionIds,
      test: t.path,
      runner: "playwright",
      level: t.level,
      origin: t.origin,
      status,
      attempts,
      durationMs: attempts.reduce((s, a) => s + a.durationMs, 0),
      error: status === "pass" ? undefined : attempts[attempts.length - 1]?.error,
      artifactIds: [],
    });
  }
  return results;
}

export async function ensureBrowsers(root: string, ws: Workspace): Promise<{ ok: boolean; log: string }> {
  const cli = playwrightCli(root);
  const args = [...cli.args, "install", ...(process.platform === "linux" ? ["--with-deps"] : []), "chromium"];
  log.info("installing Chromium for Playwright");
  const r = await runCommand({ cmd: cli.cmd, args, cwd: root, timeoutMs: 10 * 60_000, logFile: path.join(ws.artifactsDir, "logs", "playwright-install.log") });
  return { ok: r.code === 0, log: r.output };
}

export async function runPlaywright(args: {
  tests: PlanTest[];
  ws: Workspace;
  baseConfigRel: string | null;
  retries: number;
  yml: DevasignVerifyConfig | null;
  timeoutMs: number;
  artifacts: LocalArtifact[];
  configName: string;
}): Promise<{ results: RunnerResult[]; output: string; code: number | null }> {
  const { ws } = args;
  const outputDir = path.join(ws.artifactsDir, "pw", args.configName.replace(/\.config\.ts$/, ""));
  const reportFile = path.join(outputDir, "report.json");
  const cli = playwrightCli(ws.root);
  if (cli.ours) {
    // Let `.devasign/**` resolve @playwright/test without touching the repo's node_modules.
    ws.linkPackage("@playwright/test", ourPlaywrightDir());
    const pw = path.join(ourPlaywrightDir(), "..", "..", "playwright");
    if (existsSync(pw)) ws.linkPackage("playwright", path.resolve(pw));
  }
  const testDir = args.tests.every((t) => t.origin === "generated") ? path.join(ws.testsDir, "e2e") : ws.root;
  const cfgSource = generatePlaywrightConfig({ root: ws.root, baseConfigRel: args.baseConfigRel, testDir, outputDir, reportFile, retries: args.retries, webServer: webServerFromYml(args.yml) });
  const cfgPath = ws.write(path.join(".devasign", args.configName), cfgSource);
  const files = args.tests.map((t) => path.resolve(ws.root, t.path));
  log.group(`playwright ${args.configName}: ${files.length} file(s)`);
  const r = await runCommand({ cmd: cli.cmd, args: [...cli.args, "test", "--config", cfgPath, ...files], cwd: ws.root, timeoutMs: args.timeoutMs, logFile: path.join(ws.artifactsDir, "logs", `${args.configName}.log`), onLine: (l) => console.log(`  ${l}`) });
  log.endGroup();
  let report: PwReport = {};
  if (existsSync(reportFile) && statSync(reportFile).size > 0) {
    try {
      report = JSON.parse(readFileSync(reportFile, "utf8"));
    } catch (err) {
      log.warn(`could not parse the Playwright JSON report: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  const logRef = `log:pw:${args.configName}`;
  args.artifacts.push({ clientRef: logRef, kind: "log", path: path.join(ws.artifactsDir, "logs", `${args.configName}.log`), displayPath: ws.relative(path.join(ws.artifactsDir, "logs", `${args.configName}.log`)), contentType: "text/plain", criterionIds: [] });
  const results = mapReport(report, args.tests, ws, args.artifacts, r.output);
  for (const res of results) res.artifactIds = [logRef];
  return { results, output: r.output, code: r.code };
}
