// The setup pull request's own CI run: boot the config DevAsign proposed, load one page
// through it, report what happened. Every failure becomes the report, never a red check.
import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { ApiError, probeArtifacts, type ApiClient } from "./api.js";
import { uploadArtifacts } from "./artifacts.js";
import { bootManaged, cleanupAuth, redact, redactFile, type BootStepResult, type StorageState } from "./boot.js";
import { diagnosePlaywrightOutput, preflight } from "./doctor.js";
import { log, setOutput } from "./log.js";
import { writeModuleTypeShims } from "./module-type.js";
import { ensureBrowsers, runPlaywright } from "./runners/playwright.js";
import { CLI_VERSION, type BootProbeOffer, type BootReport, type DetectedSetup, type DevasignVerifyConfig, type DoctorDiagnosis, type LocalArtifact, type PlanTest } from "./types.js";
import { redactTrace } from "./trace-redact.js";
import type { Workspace } from "./workspace.js";

export const BOOT_CONFIG_NAME = "playwright.boot.config.ts";
export const BOOT_TEST_PATH = ".devasign/tests/e2e/__boot__/boot.spec.ts";

const STAGE_BY_STEP: Record<string, BootReport["stage"]> = { install: "install", build: "install", seed: "install", app: "start", login: "login" };

/** Which stage the report blames: a server's own name is never one of the fixed step names. */
export function stageForStep(failedStep: string | null, steps: BootStepResult[]): BootReport["stage"] {
  if (!failedStep) return "config";
  return STAGE_BY_STEP[failedStep] ?? (steps.some((s) => s.name === failedStep && s.kind === "server") ? "servers" : "start");
}

/** Where a finished boot stopped: DevAsign's own browser not installing is not the repo's page failing. */
export function stageForPage(ok: boolean, diagnosis: DoctorDiagnosis | null): BootReport["stage"] {
  if (ok) return "done";
  return diagnosis?.code === "browser_install_failed" ? "browsers" : "page";
}

export function readyUrlOf(yml: DevasignVerifyConfig): string {
  try {
    return new URL(yml.ready || "/", yml.url!).toString();
  } catch {
    return yml.url!;
  }
}

/** The one test the probe runs: load the ready URL, record its status, take a picture. */
export function bootSpecSource(a: { url: string; pageFile: string; shotFile: string }): string {
  const j = (v: string) => JSON.stringify(v);
  return [
    "// Generated by @devasign/verify for the setup pull request's boot check; removed with the workspace.",
    'import { test } from "@playwright/test";',
    'import { writeFileSync } from "node:fs";',
    'test("the app answers at its ready url", async ({ page }) => {',
    "  let status: number | null = null;",
    "  try {",
    `    const res = await page.goto(${j(a.url)}, { waitUntil: "load" });`,
    "    status = res ? res.status() : null;",
    "  } finally {",
    `    writeFileSync(${j(a.pageFile)}, JSON.stringify({ status }));`,
    `    await page.screenshot({ path: ${j(a.shotFile)} }).catch(() => {});`,
    "  }",
    "  if (status === null || status >= 400) throw new Error(`the app answered ${status === null ? \"nothing\" : status} at its ready url`);",
    "});",
    "",
  ].join("\n");
}

const bootTest = (): PlanTest => ({
  id: "boot",
  path: BOOT_TEST_PATH,
  content: null,
  criterionIds: [],
  level: "e2e",
  levelReason: "the boot check",
  origin: "generated",
  runner: "playwright",
  testSignature: "boot",
  strategyVersion: 1,
  targetFiles: [],
});

/** What the step summary leads with. Only a boot that failed blames the boot. */
function headline(report: BootReport, url: string | null): string[] {
  const took = (report.durationMs / 1000).toFixed(1);
  if (report.ok) return [`The app came up at ${url ?? "its url"} in ${took}s.`];
  const note = report.diagnosis ? [`> ${report.diagnosis.message}`] : [];
  if (report.stage === "browsers") return ["The app came up, but DevAsign could not install its own browser, so the page was never loaded.", ...note];
  if (report.stage === "page") return [`The app came up in ${took}s, but the page did not load.`, ...note];
  if (report.stage === "login") return [`The app came up in ${took}s, but signing in did not work.`, ...note];
  const where = report.stage === "servers" && report.failedServer ? `servers/${report.failedServer}` : report.stage;
  return [`The app did not come up — it stopped at \`${where}\`.`, ...note];
}

/** The login line, or nothing at all: a script that never ran must not be blamed. */
function loginLine(login: NonNullable<BootReport["login"]>): string | null {
  if (!login.ran) return null;
  if (login.ok) return `Signed in${login.checked ? ` (session check answered ${login.checkStatus ?? "nothing"})` : ", session not checked"}.`;
  if (login.cors) return `The session check's CORS headers did not allow the app's origin (${login.cors}).`;
  return login.checked ? `The session check answered ${login.checkStatus ?? "nothing"}.` : "The login script did not produce a usable session.";
}

export function summaryMarkdown(report: BootReport, url: string | null): string {
  const lines = headline(report, url);
  const login = report.login ? loginLine(report.login) : null;
  if (login) lines.push(login);
  if (report.page) lines.push(`The page answered ${report.page.status ?? "nothing"}.`);
  return `## DevAsign boot check\n\n${lines.join("\n\n")}\n\nDevAsign posts the result on the setup pull request.\n`;
}

type Collected = { report: BootReport; artifacts: LocalArtifact[]; logRef: string | null; shotRef: string | null };

type ProbeArgs = {
  api: ApiClient;
  probe: BootProbeOffer;
  ws: Workspace;
  yml: DevasignVerifyConfig | null;
  setup: DetectedSetup;
  sha: string;
  keep: boolean;
  testTimeoutMs: number;
  fetchImpl?: typeof fetch;
  ensureBrowsersImpl?: typeof ensureBrowsers;
};

/** undefined when the boot never reached the login step, so nothing is reported about one. */
export function loginReport(yml: DevasignVerifyConfig, boot: Awaited<ReturnType<typeof bootManaged>>): BootReport["login"] | undefined {
  if (!yml.login?.script) return undefined;
  const ran = boot.ok || boot.failedStep === "login";
  if (!ran) return undefined;
  const check = boot.check;
  return {
    ran: true,
    checked: !!check,
    ok: boot.ok,
    ...(typeof check?.status === "number" ? { checkStatus: check.status } : {}),
    ...(check?.cors ? { cors: check.cors } : {}),
  };
}

export async function bootAndLoad(args: ProbeArgs): Promise<Collected> {
  const { ws, yml } = args;
  const artifacts: LocalArtifact[] = [];
  const base: BootReport = { sha: args.sha, ok: false, stage: "config", durationMs: 0, cliVersion: CLI_VERSION, servers: [] };
  const empty = { artifacts, logRef: null, shotRef: null };

  const pre = preflight({ tests: [bootTest()], setup: args.setup, yml, repoHasPlaywrightConfig: false, env: process.env, nodeVersion: process.version });
  if (pre) {
    log.warn(`the proposed setup cannot boot yet: ${pre.message}`);
    return { report: { ...base, diagnosis: pre }, ...empty };
  }

  const bootStarted = Date.now();
  const logFiles: string[] = [];
  const traces: string[] = [];
  let state: StorageState | null = null;
  let boot: Awaited<ReturnType<typeof bootManaged>> | null = null;
  try {
    const servers = yml!.servers?.length ?? 0;
    log.info(`starting ${servers ? `${servers} server(s), then the app` : "the app"}${yml!.login?.script ? ", then signing in" : ""}`);
    boot = await bootManaged(yml!, ws, { fetchImpl: args.fetchImpl });
    for (const f of boot.handle?.logFiles ?? []) {
      logFiles.push(f);
      artifacts.push({ clientRef: `log:boot:${path.basename(f, ".log").replace(/^boot-/, "")}`, kind: "log", path: f, displayPath: ws.relative(f), contentType: "text/plain", criterionIds: [] });
    }
    const steps = boot.steps.filter((s) => s.kind === "server").map((s) => ({ name: s.name, ok: s.ok, ...(s.readyMs === undefined ? {} : { readyMs: s.readyMs }), ...(s.exitCode === undefined ? {} : { exitCode: s.exitCode }) }));
    const login = loginReport(yml!, boot);
    const partial: BootReport = { ...base, durationMs: Date.now() - bootStarted, servers: steps, ...(login ? { login } : {}) };
    if (!boot.ok) {
      const failedStep = boot.failedStep;
      const stage = stageForStep(failedStep, boot.steps);
      log.warn(`the proposed setup did not come up: ${boot.diagnosis.message}`);
      const logRef = artifacts.find((a) => a.clientRef === `log:boot:${failedStep}`)?.clientRef ?? null;
      return { report: { ...partial, stage, ...(stage === "servers" && failedStep ? { failedServer: failedStep } : {}), diagnosis: boot.diagnosis }, artifacts, logRef, shotRef: null };
    }
    state = boot.state;
    const bootMs = Date.now() - bootStarted;
    log.info(`app is up at ${boot.baseUrl}${boot.storageStatePath ? `, signed in (session ${boot.sessionChecked ? "checked" : "not checked"})` : ""}`);

    // Only the page step needs a browser, and it is unreachable unless the boot worked: a
    // doomed boot must not pay for a ~150MB download first.
    const inst = await (args.ensureBrowsersImpl ?? ensureBrowsers)(ws.root, ws);
    if (!inst.ok) log.warn("Chromium install reported a failure; continuing — the page step will say if the browser is missing");
    else setOutput("browsers", "true");

    const pageFile = path.join(ws.artifactsDir, "boot", "page.json");
    const shotFile = path.join(ws.artifactsDir, "boot", "page.png");
    mkdirSync(path.dirname(pageFile), { recursive: true });
    const spec = bootTest();
    ws.write(BOOT_TEST_PATH, bootSpecSource({ url: readyUrlOf(yml!), pageFile, shotFile }));
    writeModuleTypeShims(ws, [spec]);
    logFiles.push(path.join(ws.artifactsDir, "logs", `${BOOT_CONFIG_NAME}.log`));
    const pw: LocalArtifact[] = [];
    // The customer's own Playwright config is not spread in: this proves the app boots, not that their config loads.
    const out = await runPlaywright({
      tests: [spec],
      ws,
      baseConfigRel: null,
      retries: 0,
      yml,
      timeoutMs: args.testTimeoutMs,
      artifacts: pw,
      configName: BOOT_CONFIG_NAME,
      booted: { baseUrl: boot.baseUrl, ...(boot.storageStatePath ? { storageState: boot.storageStatePath } : {}) },
      scrub: (t) => redact(t, { envNames: yml!.env, state }),
    });
    // Only the log: a recording of a signed-in page is evidence nobody asked for here.
    artifacts.push(...pw.filter((a) => a.kind === "log"));
    traces.push(...pw.filter((a) => a.kind === "trace").map((a) => a.path));
    let status: number | null = null;
    try {
      const v = JSON.parse(readFileSync(pageFile, "utf8"));
      if (typeof v?.status === "number") status = v.status;
    } catch {
      // the browser never got far enough to write it
    }
    const passed = out.results[0]?.status === "pass";
    const ok = passed && status !== null && status < 400;
    let shotRef: string | null = null;
    if (existsSync(shotFile)) {
      shotRef = "screenshot:boot";
      artifacts.push({ clientRef: shotRef, kind: "screenshot", path: shotFile, displayPath: ws.relative(shotFile), contentType: "image/png", criterionIds: [] });
    }
    const diagnosis: DoctorDiagnosis | null = ok
      ? null
      : (diagnosePlaywrightOutput(out.output, boot.baseUrl) ?? { stage: "start", code: "app_not_ready", message: `the app answered ${status === null ? "nothing" : status} at its ready URL` });
    if (!ok) log.warn(`the app started but the page did not load: ${diagnosis!.message}`);
    return {
      report: { ...partial, ok, stage: stageForPage(ok, diagnosis), durationMs: bootMs, page: { status }, diagnosis },
      artifacts,
      logRef: pw.find((a) => a.kind === "log")?.clientRef ?? null,
      shotRef,
    };
  } finally {
    if (boot?.handle) await boot.handle.stop();
    cleanupAuth(ws);
    // Nothing leaves this job — or survives --keep — before the secrets and the session are out of it.
    for (const f of logFiles) redactFile(f, { envNames: yml?.env, state });
    if (state) for (const f of new Set(traces)) redactTrace(f, { envNames: yml?.env, state });
  }
}

/**
 * Always resolves 0: a boot the App proposed failing to start is news for the setup PR,
 * never a red check on the customer's pipeline.
 */
export async function runBootProbe(args: ProbeArgs): Promise<number> {
  const { api, probe, ws, yml } = args;
  log.info(`this is DevAsign's own setup pull request: checking that the boot config it proposes works (probe ${probe.probeId})`);
  let report: BootReport = { sha: args.sha, ok: false, stage: "config", durationMs: 0, cliVersion: CLI_VERSION, servers: [] };
  try {
    const collected = await bootAndLoad(args).catch((err) => {
      log.warn(`the boot check did not finish: ${err instanceof Error ? err.message : String(err)}`);
      return { report: { ...report, diagnosis: { stage: "start", code: "unknown", message: "the boot check did not finish" } as DoctorDiagnosis }, artifacts: [], logRef: null, shotRef: null } satisfies Collected;
    });
    report = collected.report;
    if (collected.artifacts.length) {
      const ids = await uploadArtifacts(api, probeArtifacts(probe.probeId, args.sha), collected.artifacts, probe.uploadLimits, args.fetchImpl).catch((err) => {
        log.warn(`the boot check's artifacts could not be uploaded: ${err instanceof Error ? err.message : String(err)}`);
        return new Map<string, string>();
      });
      const logId = (collected.logRef && ids.get(collected.logRef)) || [...ids.entries()].find(([ref]) => ref.startsWith("log:"))?.[1];
      const shotId = collected.shotRef ? ids.get(collected.shotRef) : undefined;
      if (logId) report = { ...report, logArtifactId: logId, ...(report.diagnosis ? { diagnosis: { ...report.diagnosis, logArtifactId: report.diagnosis.logArtifactId ?? logId } } : {}) };
      if (shotId) report = { ...report, screenshotArtifactId: shotId };
    }
    try {
      await api.bootReport(probe.probeId, report);
      log.info("boot check reported; DevAsign will comment the result on the setup pull request");
    } catch (err) {
      log.warn(`the boot check result was not accepted: ${err instanceof ApiError ? `HTTP ${err.status}` : err instanceof Error ? err.message : String(err)}`);
    }
    const scrub = (t: string) => redact(t, { envNames: yml?.env });
    setOutput(
      "outcome",
      report.ok ? "boot check: the app came up" : report.stage === "browsers" ? "boot check: the app came up, DevAsign's browser did not install" : `boot check: stopped at ${report.stage}`
    );
    if (process.env.GITHUB_STEP_SUMMARY) {
      try {
        appendFileSync(process.env.GITHUB_STEP_SUMMARY, scrub(summaryMarkdown(report, yml?.url ?? null)));
      } catch {
        // best-effort
      }
    }
  } catch (err) {
    log.warn(`the boot check could not be reported: ${err instanceof Error ? err.message : String(err)}`);
  } finally {
    if (!args.keep) ws.cleanup();
    else log.info(`kept ${ws.dir}`);
  }
  return 0;
}
